# Generated by Django 3.0.4 on 2020-06-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cteated_at',
            new_name='created_at',
        ),
    ]
